// Login
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';
export const LOGIN_SET_LOGGED = 'LOGIN_SET_LOGGED';
export const LOGIN_EMAIL_USED = 'LOGIN_EMAIL_USED';
export const LOGIN_TOKEN_USED = 'LOGIN_TOKEN_USED';
export const LOGIN_USER_TYPE = 'LOGIN_USER_TYPE';

// Companies
export const COMPANIES_IS_LOADING = 'COMPANIES_IS_LOADING';
export const COMPANIES_GET_ALL = 'COMPANIES_GET_ALL';
export const COMPANIES_GET_BY_ID = 'COMPANIES_GET_BY_ID';
export const COMPANIES_CURRENT_PAGE = 'COMPANIES_CURRENT_PAGE';
export const COMPANIES_TOTAL_RECORDS = 'COMPANIES_TOTAL_RECORDS';
export const COMPANIES_SEARCH = 'COMPANIES_SEARCH';
export const COMPANIES_NEXT_STEP = 'COMPANIES_NEXT_STEP';
export const COMPANIES_DISABLE_FIELDS = 'COMPANIES_DISABLE_FIELDS';

// Departments
export const DEPARTMENTS_IS_LOADING = 'DEPARTMENTS_IS_LOADING';
export const DEPARTMENTS_GET_ALL = 'DEPARTMENTS_GET_ALL';
export const DEPARTMENTS_CURRENT_PAGE = 'DEPARTMENTS_CURRENT_PAGE';
export const DEPARTMENTS_TOTAL_RECORDS = 'DEPARTMENTS_TOTAL_RECORDS';
export const DEPARTMENTS_SEARCH = 'DEPARTMENTS_SEARCH';

// Empolyees
export const EMPLOYEES_IS_LOADING = 'EMPLOYEES_IS_LOADING';
export const EMPLOYEES_GET_ALL = 'EMPLOYEES_GET_ALL';
export const EMPLOYEES_CURRENT_PAGE = 'EMPLOYEES_CURRENT_PAGE';
export const EMPLOYEES_TOTAL_RECORDS = 'EMPLOYEES_TOTAL_RECORDS';
export const EMPLOYEES_SEARCH = 'EMPLOYEES_SEARCH';

// Products
export const PRODUCTS_IS_LOADING = 'PRODUCTS_IS_LOADING';
export const PRODUCTS_GET_ALL = 'PRODUCTS_GET_ALL';
export const PRODUCTS_CURRENT_PAGE = 'PRODUCTS_CURRENT_PAGE';
export const PRODUCTS_TOTAL_RECORDS = 'PRODUCTS_TOTAL_RECORDS';
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
export const PRODUCTS_NEXT_STEP = 'PRODUCTS_NEXT_STEP';
export const PRODUCTS_DISABLE_FIELDS = 'PRODUCTS_DISABLE_FIELDS';

// Variations
export const VARIATIONS_IS_LOADING = 'VARIATIONS_IS_LOADING';
export const VARIATIONS_GET_ALL = 'VARIATIONS_GET_ALL';
export const VARIATIONS_CURRENT_PAGE = 'VARIATIONS_CURRENT_PAGE';
export const VARIATIONS_TOTAL_RECORDS = 'VARIATIONS_TOTAL_RECORDS';
export const VARIATIONS_SEARCH = 'VARIATIONS_SEARCH';

// Orders
export const ORDERS_IS_LOADING = 'ORDERS_IS_LOADING';
export const ORDERS_GET_ALL = 'ORDERS_GET_ALL';
export const ORDERS_GET_BY_ID = 'ORDERS_GET_BY_ID';
export const ORDERS_CURRENT_PAGE = 'ORDERS_CURRENT_PAGE';
export const ORDERS_TOTAL_RECORDS = 'ORDERS_TOTAL_RECORDS';
export const ORDERS_SEARCH = 'ORDERS_SEARCH';
export const ORDERS_GET_ALL_NOT_PRINTED = 'ORDERS_GET_ALL_NOT_PRINTED';
