// Login
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';
export const LOGIN_SET_LOGGED = 'LOGIN_SET_LOGGED';

// Companies
export const COMPANIES_IS_LOADING = 'COMPANIES_IS_LOADING';
export const COMPANIES_GET_ALL = 'COMPANIES_GET_ALL';
export const COMPANIES_GET_BY_ID = 'COMPANIES_GET_BY_ID';
export const COMPANIES_CURRENT_PAGE = 'COMPANIES_CURRENT_PAGE';
export const COMPANIES_TOTAL_RECORDS = 'COMPANIES_TOTAL_RECORDS';
export const COMPANIES_SEARCH = 'COMPANIES_SEARCH';
export const COMPANIES_NEXT_STEP = 'COMPANIES_NEXT_STEP';
export const COMPANIES_DISABLE_FIELDS = 'COMPANIES_DISABLE_FIELDS';

// Departments
export const DEPARTMENTS_IS_LOADING = 'DEPARTMENTS_IS_LOADING';
export const DEPARTMENTS_GET_ALL = 'DEPARTMENTS_GET_ALL';
export const DEPARTMENTS_CURRENT_PAGE = 'DEPARTMENTS_CURRENT_PAGE';
export const DEPARTMENTS_TOTAL_RECORDS = 'DEPARTMENTS_TOTAL_RECORDS';
export const DEPARTMENTS_SEARCH = 'DEPARTMENTS_SEARCH';

// Empolyees
export const EMPLOYEES_IS_LOADING = 'EMPLOYEES_IS_LOADING';
export const EMPLOYEES_GET_ALL = 'EMPLOYEES_GET_ALL';
export const EMPLOYEES_CURRENT_PAGE = 'EMPLOYEES_CURRENT_PAGE';
export const EMPLOYEES_TOTAL_RECORDS = 'EMPLOYEES_TOTAL_RECORDS';
export const EMPLOYEES_SEARCH = 'EMPLOYEES_SEARCH';
